//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_AKTIFURETIM
    {
        public string SIPARIS_NO { get; set; }
        public string MAKINA { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public Nullable<decimal> PLANLANAN_MIKTAR { get; set; }
        public string CARI_ADI { get; set; }
        public string ISEMRI { get; set; }
        public Nullable<double> URETIM_MIKTARI { get; set; }
        public int ID { get; set; }
    }
}
