//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_99_DEPO_BAKIYE
    {
        public string SON_HAREKET { get; set; }
        public string STOK_ADI { get; set; }
        public decimal BAKIYE { get; set; }
        public Nullable<long> SIRA { get; set; }
    }
}
