//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_DEPOLAR_RAPOR
    {
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public Nullable<decimal> HAMMADDE_DEPO { get; set; }
        public Nullable<decimal> HURDA_DEPO { get; set; }
        public Nullable<decimal> EGESAN_DEPO { get; set; }
        public Nullable<decimal> EGEOFSET_DEPO { get; set; }
        public Nullable<decimal> EGEMET_DEPO { get; set; }
        public Nullable<decimal> EGEM2_DEPO { get; set; }
        public Nullable<decimal> EGEM143_DEPO { get; set; }
    }
}
