//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PILOTEntities : DbContext
    {
        public PILOTEntities()
            : base("name=PILOTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EGEM_DEPOLAR_RAPOR> EGEM_DEPOLAR_RAPOR { get; set; }
        public virtual DbSet<EGEM_PORT_AIRSALIYE> EGEM_PORT_AIRSALIYE { get; set; }
        public virtual DbSet<EGEM_AKTIFURETIM> EGEM_AKTIFURETIM { get; set; }
        public virtual DbSet<EGEM_DEPO99BAKIYE> EGEM_DEPO99BAKIYE { get; set; }
        public virtual DbSet<EGEM_143_DEPO_BAKIYE> EGEM_143_DEPO_BAKIYE { get; set; }
    }
}
