//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_DEPO_VARDIYA
    {
        public int ID { get; set; }
        public string TARIH { get; set; }
        public string VARDIYA { get; set; }
        public string DEPO_SORUMLU1 { get; set; }
        public string DEPO_SORUMLU2 { get; set; }
        public string KIMYASAL_DEPO { get; set; }
        public string FORKLIFT_OPERATOR1 { get; set; }
        public string FORKLIFT_OPERATOR2 { get; set; }
        public string FORLIFT_DURUM { get; set; }
        public string MAKINE_HAMMADDE_BESLEME_VERILEN { get; set; }
        public string MAKINE_HAMMADDE_BESLEME_SIRADAKI { get; set; }
        public string GELEN_KAMYON_ADET { get; set; }
        public string GELEN_DIGER_URUN { get; set; }
        public string SILINDIR_GIRIS { get; set; }
        public string BEKLEYEN_DAT { get; set; }
        public string BEKLEYEN_MAL_KABUL { get; set; }
        public string TUTANAK { get; set; }
        public string ACIKLAMA { get; set; }
        public string PALET_DURUMU { get; set; }
        public string IDARI_ISLEM { get; set; }
        public string VARDIYA_KONTROL { get; set; }
        public string MUREKKEP_BILGI { get; set; }
        public string AKU_SARJ { get; set; }
        public string DEPO_GELIS_SATINALMA { get; set; }
        public string GECE_IS { get; set; }
        public string KIMYASAL_DEPO_SORUMLU { get; set; }
    }
}
