//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_ESNEK_DILIMLEME_KALITE
    {
        public int ID { get; set; }
        public string URUN_KODU { get; set; }
        public string URUN_ADI { get; set; }
        public string SIPARIS_NO { get; set; }
        public Nullable<System.DateTime> ZAMAN { get; set; }
        public Nullable<int> BOBIN_NO { get; set; }
        public string DILME_ENI { get; set; }
        public string FOTOSEL_ARALIGI { get; set; }
        public string ACILIS_YONU { get; set; }
        public string IC_CAP { get; set; }
        public string EK_SAYI { get; set; }
        public string BOBIN_CAP { get; set; }
        public string GORSEL_KONTROL { get; set; }
        public string KESIM_KAYIK { get; set; }
        public string TONLAMA { get; set; }
        public string SAKAL { get; set; }
        public string CIZGI { get; set; }
        public string RENK_UYGUN { get; set; }
        public string SARIM_DUZGUN { get; set; }
        public string BOBIN_EKI_KONTROL { get; set; }
        public string BOBIN_BARKOD_OKUT { get; set; }
        public string BARKOD_KONTROL { get; set; }
        public string KALITE_ONAY { get; set; }
        public string MAKINE { get; set; }
    }
}
