//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_MVC_USER
    {
        public int ID { get; set; }
        public string AD_SOYAD { get; set; }
        public string SIFRE { get; set; }
        public string ROL { get; set; }
    }
}
