//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_OFSET_BASKI_KALITE
    {
        public int ID { get; set; }
        public string SIPARISNO { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public string PROSES { get; set; }
        public string TARIH { get; set; }
        public string SAAT { get; set; }
        public string CALISILAN_MKN { get; set; }
        public string URUN_ADI_KNT { get; set; }
        public string PALET_NO { get; set; }
        public string HAMMADDE_KONTROL { get; set; }
        public string GRAMAJ_KONTROL { get; set; }
        public string EBAT_KONTROL { get; set; }
        public string CAPRAZ_KONTROL { get; set; }
        public string YELPAZE_KONTROL { get; set; }
        public string YAPISMA_KONTROL { get; set; }
        public string SU_YOLU_KONTROL { get; set; }
        public string MUREKKEP_KONTROL { get; set; }
        public string ARTWORK_UYGUNLUK { get; set; }
        public string BICAK_KONTROL { get; set; }
        public string POZA_KONTROL { get; set; }
        public string TONLAMA_SAKAL_KONTROL { get; set; }
        public string GORSEL_KONTROL { get; set; }
        public string LAK_BOS_KONTROL { get; set; }
        public string LAK_AL_KONTROL { get; set; }
        public string PARLAKLIK { get; set; }
        public string ASINMA { get; set; }
        public string COF_KINETIK_TEST { get; set; }
        public string COF_STATIK_TEST { get; set; }
        public string ISIL_YAPISMA { get; set; }
        public string RENK_KONTROL { get; set; }
        public string BARKOD_KONTROL { get; set; }
        public string ASETAT_KONTROL { get; set; }
        public string KORONA_YONU { get; set; }
        public string SILIKONLU_BANT { get; set; }
        public string KONTROL_EDEN { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
