//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_DOF_TAKIP
    {
        public int ID { get; set; }
        public string KAYIT_YAPAN { get; set; }
        public string TARIH { get; set; }
        public string UYGUNSUZLUK_FAALIYET { get; set; }
        public string UYGUNSUZLUK_SUREC { get; set; }
        public string UYGUNSUZLUK_TANIMI { get; set; }
        public string MUSTERI_ADI { get; set; }
        public string STOK_ADI { get; set; }
        public string STOK_KODU { get; set; }
        public string SIPARIS_NO { get; set; }
        public string BIRIM { get; set; }
        public string OPERATOR_ADI { get; set; }
        public string MALZEME_KODU { get; set; }
        public string MALZEME_ADI { get; set; }
        public Nullable<int> HATALI_URUN_MIKTARI { get; set; }
        public string UYGUNSUZ_MAKINA { get; set; }
        public string UYGUNSUZ_GRUP { get; set; }
        public string UYGUNSUZ_KOK_NEDEN { get; set; }
        public string UYGUNSUZ_KOK_NEDEN_ACIK { get; set; }
        public string DUZELTME_FAALIYET { get; set; }
        public Nullable<System.DateTime> DUZELTME_FAALIYET_TARIH { get; set; }
        public string DUZELTME_ISLEM { get; set; }
        public string ONLEYICI_FAALIYET { get; set; }
        public Nullable<System.DateTime> ONLEYICI_FAALIYET_TARIH { get; set; }
        public string YAPILACAKLAR_ACIKLAMA_1 { get; set; }
        public string YAPILACAKLAR_SORUMLU_1 { get; set; }
        public string YAPILACAKLAR_TARIH_1 { get; set; }
        public string YAPILACAKLAR_ACIKLAMA_2 { get; set; }
        public string YAPILACAKLAR_SORUMLU_2 { get; set; }
        public string YAPILACAKLAR_TARIH_2 { get; set; }
        public string TAKIP_SONUCU_1 { get; set; }
        public string TAKIP_TARIH_1 { get; set; }
        public string TAKIP_SONUCU_2 { get; set; }
        public string TAKIP_TARIH_2 { get; set; }
        public string YGG_KARARI { get; set; }
        public string YGG_TARIH { get; set; }
        public string TAKIP_SONUCU_3 { get; set; }
        public string TAKIP_TAIH_3 { get; set; }
        public string TAKIP_SONUCU_4 { get; set; }
        public string TAKIP_TARIH_4 { get; set; }
        public string DOF_SAHIP { get; set; }
        public string KOK_NEDEN_AD_SOY { get; set; }
        public string KOK_NEDEN_BIRIM { get; set; }
        public string KOK_NEDEN_UNVAN { get; set; }
        public string KOK_NEDEN_ANALIZ_KONU { get; set; }
        public string KOK_NEDEN_BAS_TAR { get; set; }
        public string KOK_NEDEN_BIT_TAR { get; set; }
        public string KOK_NEDEN1 { get; set; }
        public string KOK_NEDEN2 { get; set; }
        public string KOK_NEDEN3 { get; set; }
        public string KOK_NEDEN4 { get; set; }
        public string COZUM { get; set; }
        public string ONERI { get; set; }
        public string DF_KAPATMA_SURE { get; set; }
        public string DOF_DURUM { get; set; }
        public string HATA_BULAN { get; set; }
        public Nullable<int> HATALI_MALZEME_MIKTARI { get; set; }
        public string HATALI_MALZEME_BIRIM { get; set; }
        public Nullable<decimal> KREDI_NOTU { get; set; }
        public Nullable<System.DateTime> GECICI_AKSIYON { get; set; }
        public Nullable<System.DateTime> KALICI_AKSIYON { get; set; }
        public Nullable<int> DURUS_SURE { get; set; }
        public string SATINALMA_KARAR { get; set; }
        public string SATINALMA_TEDARIK_AKSIYON { get; set; }
        public string DOF_BILGI { get; set; }
        public string PACKAGE_ID { get; set; }
        public string UYGUNSUZLUK_TANIMI_SATINALMA { get; set; }
        public string TEDARIKCI_AKSIYONU_SATINALMA { get; set; }
        public string IMAGE_1 { get; set; }
        public string IMAGE_1_FILE { get; set; }
        public string IMAGE_2 { get; set; }
        public string IMAGE_2_FILE { get; set; }
        public string IMAGE_3 { get; set; }
        public string IMAGE_3_FILE { get; set; }
        public string IMAGE_4 { get; set; }
        public string IMAGE_4_FILE { get; set; }
        public string IMAGE_5 { get; set; }
        public string IMAGE_5_FILE { get; set; }
        public string IMAGE_6 { get; set; }
        public string IMAGE_6_FILE { get; set; }
        public string IMAGE_7 { get; set; }
        public string IMAGE_7_FILE { get; set; }
        public string IMAGE_8 { get; set; }
        public string IMAGE_8_FILE { get; set; }
        public string IMAGE_9 { get; set; }
        public string IMAGE_9_FILE { get; set; }
        public string IMAGE_10 { get; set; }
        public string IMAGE_10_FILE { get; set; }
        public string IMAGE_11 { get; set; }
        public string IMAGE_11_FILE { get; set; }
        public string IMAGE_12 { get; set; }
        public string IMAGE_12_FILE { get; set; }
        public string IMAGE_13 { get; set; }
        public string IMAGE_13_FILE { get; set; }
        public string IMAGE_14 { get; set; }
        public string IMAGE_14_FILE { get; set; }
        public string IMAGE_15 { get; set; }
        public string IMAGE_15_FILE { get; set; }
        public string IMAGE_16 { get; set; }
        public string IMAGE_16_FILE { get; set; }
        public string IMAGE_17 { get; set; }
        public string IMAGE_17_FILE { get; set; }
        public string IMAGE_18 { get; set; }
        public string IMAGE_18_FILE { get; set; }
        public string IMAGE_19 { get; set; }
        public string IMAGE_19_FILE { get; set; }
        public string IMAGE_20 { get; set; }
        public string IMAGE_20_FILE { get; set; }
    }
}
