//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_PROJESILINDIR_TALEP
    {
        public string SIPARIS_NO { get; set; }
        public string TALEP_NO { get; set; }
        public string CARI_KODU { get; set; }
        public string CARI_ISIM { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public string SIPARIS_TARIHI { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
    }
}
