//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_GRAVUR_KALITE
    {
        public int ID { get; set; }
        public string urun_kodu { get; set; }
        public string urun_adi { get; set; }
        public string sipno { get; set; }
        public string tarih { get; set; }
        public string saat { get; set; }
        public string palet_no { get; set; }
        public string hammadde_kontrol { get; set; }
        public string hammadde_fiziki { get; set; }
        public string silindir_kod_kontrol { get; set; }
        public string baski_icerik { get; set; }
        public string baski_register { get; set; }
        public string onay_num_renk_gorsel { get; set; }
        public string onay_num_renk_spectro { get; set; }
        public string yelpaze_renk_kont { get; set; }
        public string barkod_okut { get; set; }
        public string isil_yapis_kont { get; set; }
        public string parlaklik { get; set; }
        public string cof_test_dinamik { get; set; }
        public string cof_test_statik { get; set; }
        public string asinma_test { get; set; }
        public string baski_hata { get; set; }
        public string silindir_vuruk { get; set; }
        public string lak_kuruma { get; set; }
        public string bicak_film { get; set; }
        public string kesim_gorsel { get; set; }
        public string kesim_ebat { get; set; }
        public string tabaka_hasar { get; set; }
        public string montaj_pilyaj { get; set; }
        public string kirim_direnc { get; set; }
        public string kutu_yapisma { get; set; }
        public string emdeb_gorsel { get; set; }
        public string emdeb_register { get; set; }
        public string emdeb_kontrol { get; set; }
        public string kulakcik_katlan { get; set; }
        public string palet_etiket { get; set; }
        public string kontrol_onay { get; set; }
        public string bobin_patlak { get; set; }
        public string MAKINE { get; set; }
        public string yedek { get; set; }
        public Nullable<System.DateTime> zaman { get; set; }
        public string bundle_yuksek { get; set; }
        public string hammadde_oba { get; set; }
        public string palet_yerlesim { get; set; }
        public string palet_gorsel { get; set; }
        public string hammadde_gorsel_kontrol { get; set; }
        public string makine_temiz_renk { get; set; }
        public string kirpinti_kontrol { get; set; }
    }
}
