//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_ESNEK_BASKI_KALITE
    {
        public int ID { get; set; }
        public string URUN_KODU { get; set; }
        public string URUN_ADI { get; set; }
        public string SIPARIS_NO { get; set; }
        public string ZAMAN { get; set; }
        public Nullable<int> BOBIN_NO { get; set; }
        public string HAMMADDE_KONTROL { get; set; }
        public string BOBIN_ENI { get; set; }
        public string FOTOSEL_ARALIGI { get; set; }
        public string NET_BASKI_ENI { get; set; }
        public string BASKI_YONU { get; set; }
        public string FILM_TIPI { get; set; }
        public string BARKOD_OKUNUR { get; set; }
        public string ACILIS_YONU { get; set; }
        public string ARKA_KAPANMA_SEKLI { get; set; }
        public string ICERIK_KONTROL { get; set; }
        public string RENK_UYGUN { get; set; }
        public string RENK_UYGUN_GOZ { get; set; }
        public string BASKI_KAYIK { get; set; }
        public string GORSEL_KONTROL { get; set; }
        public string ADEZYON { get; set; }
        public string KURUMA { get; set; }
        public string TONLAMA { get; set; }
        public string SAKAL { get; set; }
        public string CIZGI { get; set; }
        public string ISIL_YAPISMA { get; set; }
        public string MUREKKEP_MIKTAR { get; set; }
        public string BIRIM_AGIRLIK { get; set; }
        public string COF { get; set; }
        public string GC_TEST { get; set; }
        public string BOBIN_ICBAYRAK_SAYI { get; set; }
        public string MAKINE { get; set; }
        public string KONTROL_ONAY { get; set; }
        public string SILINDIR_KOD_KONTROL { get; set; }
        public string GLOSS { get; set; }
        public string NOK_GORSEL { get; set; }
        public string GORSEL_ADRES { get; set; }
        public string CITILEME { get; set; }
    }
}
