//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_DOFLIST
    {
        public int ID { get; set; }
        public string TARIH { get; set; }
        public string KAYIT_YAPAN { get; set; }
        public string UYGUNSUZLUK_FAALIYET { get; set; }
        public string UYGUNSUZLUK_SUREC { get; set; }
        public string UYGUNSUZLUK_TANIMI { get; set; }
        public string IMAGE_1 { get; set; }
        public string IMAGE_2 { get; set; }
        public string IMAGE_3 { get; set; }
        public string IMAGE_4 { get; set; }
    }
}
