//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_ESNEK_LAMINASYON_KALITE
    {
        public int ID { get; set; }
        public string URUN_KODU { get; set; }
        public string URUN_ADI { get; set; }
        public string SIPARIS_NO { get; set; }
        public string MAKINE { get; set; }
        public Nullable<System.DateTime> ZAMAN { get; set; }
        public Nullable<int> BOBIN_NO { get; set; }
        public string BOBIN_ENI { get; set; }
        public string FOTOSEL_ARALIGI { get; set; }
        public string AL_FOLYO_YONU { get; set; }
        public string TUTKAL_GRAMAJ { get; set; }
        public string BIRIM_AGIRLIK { get; set; }
        public string YAPISMA_KONTROL { get; set; }
        public string GORSEL_KONTROL { get; set; }
        public string BENCIK_KONTROL { get; set; }
        public string ISIL_YAPISMA_KONT { get; set; }
        public string LAMINASYON_KUVVETI { get; set; }
        public string COF_TEST { get; set; }
        public string KALITE_ONAY { get; set; }
    }
}
