//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_OFSET_BITIRME_KALITE
    {
        public int ID { get; set; }
        public string SIPARISNO { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public string PROSES { get; set; }
        public string TARIH { get; set; }
        public string SAAT { get; set; }
        public string CALISILAN_MKN { get; set; }
        public string URUN_ADI_KNT { get; set; }
        public string PALET_NO { get; set; }
        public string HAMMADDE_KONTROL { get; set; }
        public string SU_YOLU { get; set; }
        public string ARTWORK_UYGUNLUK { get; set; }
        public string BICAK_FILM_KONTROL { get; set; }
        public string GORSEL_KONTROL { get; set; }
        public string BARKOD_KONTROL { get; set; }
        public string PILYAJ_KONTROL { get; set; }
        public string KASIM_PATLATMA { get; set; }
        public string KIRIM_DIRENCI { get; set; }
        public string NIK_YERLERI_KONTROL { get; set; }
        public string EMBOSS_DEBOSS_KONTROL { get; set; }
        public string EMBOSS_DEBOSS_REGISTER { get; set; }
        public string EMBOSS_DEBOSS_KONTROL2 { get; set; }
        public string TUM_PZS_KONT { get; set; }
        public string TS_UYGUNLUK { get; set; }
        public string PALET_GENEL_KONT { get; set; }
        public string ACIKLAMA { get; set; }
        public string KONTROL_EDEN { get; set; }
        public string BUNDLE_YUKSEK { get; set; }
    }
}
