//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_KALITE_VARDIYA
    {
        public int ID { get; set; }
        public string TARIH { get; set; }
        public string VARDIYA { get; set; }
        public string KALITE_VARDIYA_SORUMLU1 { get; set; }
        public string KALITE_VARDIYA_SORUMLU2 { get; set; }
        public string K_PROSESS_1 { get; set; }
        public string K_PROSESS_2 { get; set; }
        public string K_PROSESS_3 { get; set; }
        public string K_PROSESS_4 { get; set; }
        public string K_PROSESS_5 { get; set; }
        public string K_PROSESS_6 { get; set; }
        public string K_PROSESS_1_MAK { get; set; }
        public string K_PROSESS_2_MAK { get; set; }
        public string K_PROSESS_3_MAK { get; set; }
        public string K_PROSESS_4_MAK { get; set; }
        public string K_PROSESS_5_MAK { get; set; }
        public string K_PROSESS_6_MAK { get; set; }
        public string LEM1_ACIK1 { get; set; }
        public string LEM1_ACIK2 { get; set; }
        public string LEM1_ACIK3 { get; set; }
        public string LEM1_ACIK4 { get; set; }
        public string LEM1_BAS_AW { get; set; }
        public string LEM1_MAKINE_DENEME { get; set; }
        public string LEM2_ACIK1 { get; set; }
        public string LEM2_ACIK2 { get; set; }
        public string LEM2_ACIK3 { get; set; }
        public string LEM2_ACIK4 { get; set; }
        public string LEM2_BAS_AW { get; set; }
        public string LEM2_MAKINE_DENEME { get; set; }
        public string LEM3_ACIK1 { get; set; }
        public string LEM3_ACIK2 { get; set; }
        public string LEM3_ACIK3 { get; set; }
        public string LEM3_ACIK4 { get; set; }
        public string LEM3_BAS_AW { get; set; }
        public string LEM3_MAKINE_DENEME { get; set; }
        public string KBA_ACIK1 { get; set; }
        public string KBA_ACIK2 { get; set; }
        public string KBA_ACIK3 { get; set; }
        public string KBA_ACIK4 { get; set; }
        public string KBA_BAS_AW { get; set; }
        public string KBA_MAKINE_DENEME { get; set; }
        public string R700_ACIK1 { get; set; }
        public string R700_ACIK2 { get; set; }
        public string R700_ACIK3 { get; set; }
        public string R700_ACIK4 { get; set; }
        public string R700_BAS_AW { get; set; }
        public string R700_MAKINE_DENEME { get; set; }
        public string B102_ACIK1 { get; set; }
        public string B102_ACIK2 { get; set; }
        public string B102_ACIK3 { get; set; }
        public string B102_ACIK4 { get; set; }
        public string B102_BAS_AW { get; set; }
        public string B102_MAKINE_DENEME { get; set; }
        public string B104_ACIK1 { get; set; }
        public string B104_ACIK2 { get; set; }
        public string B104_ACIK3 { get; set; }
        public string B104_ACIK4 { get; set; }
        public string B104_BAS_AW { get; set; }
        public string B104_MAKINE_DENEME { get; set; }
        public string B106P_ACIK1 { get; set; }
        public string B106P_ACIK2 { get; set; }
        public string B106P_ACIK3 { get; set; }
        public string B106P_ACIK4 { get; set; }
        public string B106P_BAS_AW { get; set; }
        public string B106P_MAKINE_DENEME { get; set; }
        public string B106L_ACIK1 { get; set; }
        public string B106L_ACIK2 { get; set; }
        public string B106L_ACIK3 { get; set; }
        public string B106L_ACIK4 { get; set; }
        public string B106L_BAS_AW { get; set; }
        public string B106L_MAKINE_DENEME { get; set; }
        public string EXPERTFOIL_ACIK1 { get; set; }
        public string EXPERTFOIL_ACIK2 { get; set; }
        public string EXPERTFOIL_ACIK3 { get; set; }
        public string EXPERTFOIL_ACIK4 { get; set; }
        public string EXPERTFOIL_BAS_AW { get; set; }
        public string EXPERTFOIL_MAKINE_DENEME { get; set; }
        public string FOILMASTER_ACIK1 { get; set; }
        public string FOILMASTER_ACIK2 { get; set; }
        public string FOILMASTER_ACIK3 { get; set; }
        public string FOILMASTER_ACIK4 { get; set; }
        public string FOILMASTER_BAS_AW { get; set; }
        public string FOILMASTER_MAKINE_DENEME { get; set; }
        public string MILLTEX_ACIK1 { get; set; }
        public string MILLTEX_ACIK2 { get; set; }
        public string MILLTEX_ACIK3 { get; set; }
        public string MILLTEX_ACIK4 { get; set; }
        public string MILLTEX_BAS_AW { get; set; }
        public string MILLTEX_MAKINE_DENEME { get; set; }
        public string POLAR_ACIK1 { get; set; }
        public string POLAR_ACIK2 { get; set; }
        public string POLAR_ACIK3 { get; set; }
        public string POLAR_ACIK4 { get; set; }
        public string POLAR_BAS_AW { get; set; }
        public string POLAR_MAKINE_DENEME { get; set; }
        public string OMEGA_ACIK1 { get; set; }
        public string OMEGA_ACIK2 { get; set; }
        public string OMEGA_ACIK3 { get; set; }
        public string OMEGA_ACIK4 { get; set; }
        public string OMEGA_BAS_AW { get; set; }
        public string OMEGA_MAKINE_DENEME { get; set; }
        public string PENCERE_ACIK1 { get; set; }
        public string PENCERE_ACIK2 { get; set; }
        public string PENCERE_ACIK3 { get; set; }
        public string PENCERE_ACIK4 { get; set; }
        public string PENCERE_BAS_AW { get; set; }
        public string PENCERE_MAKINE_DENEME { get; set; }
        public string ROTOMEC_ACIK1 { get; set; }
        public string ROTOMEC_ACIK2 { get; set; }
        public string ROTOMEC_ACIK3 { get; set; }
        public string ROTOMEC_ACIK4 { get; set; }
        public string ROTOMEC_BAS_AW { get; set; }
        public string ROTOMEC_MAKINE_DENEME { get; set; }
        public string TITAN_ACIK1 { get; set; }
        public string TITAN_ACIK2 { get; set; }
        public string TITAN_ACIK3 { get; set; }
        public string TITAN_ACIK4 { get; set; }
        public string TITAN_BAS_AW { get; set; }
        public string TITAN_MAKINE_DENEME { get; set; }
        public string REVOMAC_ACIK1 { get; set; }
        public string REVOMAC_ACIK2 { get; set; }
        public string REVOMAC_ACIK3 { get; set; }
        public string REVOMAC_ACIK4 { get; set; }
        public string REVOMAC_BAS_AW { get; set; }
        public string REVOMAC_MAKINE_DENEME { get; set; }
        public string NORD_ACIK1 { get; set; }
        public string NORD_ACIK2 { get; set; }
        public string NORD_ACIK3 { get; set; }
        public string NORD_ACIK4 { get; set; }
        public string NORD_BAS_AW { get; set; }
        public string NORD_MAKINE_DENEME { get; set; }
        public string ESNEK_AKTAR_ACIK1 { get; set; }
        public string ESNEK_AKTAR_ACIK2 { get; set; }
        public string ESNEK_AKTAR_ACIK3 { get; set; }
        public string ESNEK_AKTAR_ACIK4 { get; set; }
        public string ESNEK_AKTAR_BAS_AW { get; set; }
        public string ESNEK_AKTAR_MAKINE_DENEME { get; set; }
        public string BASKI_PROVA { get; set; }
        public string ARIZA_DURUS { get; set; }
        public string CREASE_TOLERANS { get; set; }
        public string COF_OLCUMU { get; set; }
        public string TEST_YAPILAMAYAN { get; set; }
        public string HERHANGI_SEBEP { get; set; }
        public string TESPIT_NOK { get; set; }
        public string ACIK_DOF { get; set; }
        public string HATA_PALET { get; set; }
        public string YURU_ONAY { get; set; }
        public string KATLAMA_ARSIV { get; set; }
        public string UYGUNSUZ_HAMMADDE { get; set; }
        public string DURDURULAN_ONAY { get; set; }
        public string ARIZALI_CIHAZ { get; set; }
        public string GELMEYEN_PERSONEL { get; set; }
        public string IDARI_SORUN { get; set; }
        public string LEMANIC_SAHA { get; set; }
        public string OFFSET_SAHA { get; set; }
        public string ROTOMEC_SAHA { get; set; }
        public string AYIKLAMA_SAHA { get; set; }
        public string LABORATUAR_SAHA { get; set; }
        public string DIGER { get; set; }
    }
}
