//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEM_MVC.Models.EntityEgem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EO_GRAVUR_VARDIYA
    {
        public int ID { get; set; }
        public string VARDIYA { get; set; }
        public string TARIH { get; set; }
        public string ISEMRI { get; set; }
        public string URETILEN_PALET { get; set; }
        public string DIE_VURUSU { get; set; }
        public string VARD_CALISAN { get; set; }
        public string MAKINE_HIZ { get; set; }
        public string RULO_TEM { get; set; }
        public string FOTOSEL_TEM { get; set; }
        public string PRESOR_TEM { get; set; }
        public string GOZAYNA_TEM { get; set; }
        public string UNITE_TEM { get; set; }
        public string ZEMIN_EPOKSI_TEM { get; set; }
        public string EMERGENCY_KONTR { get; set; }
        public string EMBOS_UNIT { get; set; }
        public string KESIM_BOLUM { get; set; }
        public string MONOMATIN_KONT { get; set; }
        public string PALETLEME_TEM { get; set; }
        public string LEMANIC_URETIM_ALANI { get; set; }
        public string ARABA_PARCA { get; set; }
        public string MAKINE_ARIZA { get; set; }
        public string BOBIN_MUREKKEP { get; set; }
        public string SILINDIR { get; set; }
        public string DIGER { get; set; }
        public string TESLIM_EDEN { get; set; }
        public string TESLIM_ALAN { get; set; }
        public string RULO_TEM1 { get; set; }
        public string FOTOSEL_TEM1 { get; set; }
        public string PRESOR_TEM1 { get; set; }
        public string GOZAYNA_TEM1 { get; set; }
        public string UNITE_TEM1 { get; set; }
        public string ZEMIN_EPOKSI_TEM1 { get; set; }
        public string EMERGENCY_KONTR1 { get; set; }
        public string EMBOS_UNIT1 { get; set; }
        public string KESIM_BOLUM1 { get; set; }
        public string MONOMATIN_KONT1 { get; set; }
        public string PALETLEME_TEM1 { get; set; }
        public string LEMANIC_URETIM_ALANI1 { get; set; }
        public string ARABA_PARCA1 { get; set; }
        public string MAKINE_ARIZA1 { get; set; }
        public string BOBIN_MUREKKEP1 { get; set; }
        public string SILINDIR1 { get; set; }
        public string ISDEGISIM_SAY { get; set; }
        public string TOP_FIRE { get; set; }
        public string URUN_KODU { get; set; }
        public string MAKINE { get; set; }
    }
}
